### PR TITLE
Add setter for UPnP settings

### PR DESCRIPTION
**Pull request by chrisboyle**
I find on my MX6203-KE that UPnP stops accepting connections after a few days (with Home Assistant monitoring the traffic statistics from UPnP).

Turning UPnP off and on is sufficient to fix it, so I want to automate that.

### CODE REVIEW

**Comment by uvjim** [comment]
Hi, completely didn't see this come in. I'll take a look today and get it merged if all is well.

**Comment by uvjim** [comment]
Hope you're OK with this.  I've made a couple of changes and additions in the PR.  Let me know, if that's OK and I'll get it merged.
I've done a quick test here and all seems fine.

**Comment by chrisboyle** [comment]
Looks great, thank you :+1:

**Comment by uvjim** [comment]
As you probably know already, this functionality won't be available to the HASS integration until the next version of this module is released and the version bumped in the integration.  Hopefully, I'll get a chance to do that later today.

**Comment by uvjim** [comment]
Apologies for out of the blue contact. I'm making some updates to the HASS integration. Did you want me to look at putting a toggle in for the UPnP state? The first pass will be just the overall state rather than the two individual UPnP features as well.

**Comment by chrisboyle** [comment]
That would be very helpful, thank you. I keep meaning to do it myself but haven't got around to it.

**Comment by uvjim** [comment]
I pre-empted your response whilst watching football last night (we won 5-0 thankfully).  It should be available in [2024.11.1b4](https://github.com/uvjim/linksys_velop/releases/tag/2024.11.1b4) of the integration, which I pushed last night.

**Pull request merged**
